services:
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    restart: unless-stopped
    environment:
      OCCURRENCE_WEIGHT: "0.001"
      EXTENSIONS_STORAGE_MODE: weaviate
      ENABLE_COMPOUND_SPLITTING: "false"
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
    expose:
      - "9999"

  weaviate:
    image: semitechnologies/weaviate:1.27.0
    depends_on:
      - contextionary
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6060:6060"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CONTEXTIONARY_URL: contextionary:9999
      CLUSTER_HOSTNAME: node1
    volumes:
      - weaviate-data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  sync-worker:
    build: .
    depends_on:
      weaviate:
        condition: service_healthy
    restart: unless-stopped
    environment:
      JOURNEY_AGENT_DB_PATH: /app/data/channels_db/users_channels.db
      CHANNEL_SYNC_INTERVAL_HOURS: "6"
      CHANNEL_MESSAGES_LIMIT: "10"
      WEAVIATE_URL: http://weaviate:8080
      JOURNEY_AGENT_SEED_TEST_CHANNELS: "true"
      TELEGRAM_APP_API_ID: "${TELEGRAM_APP_API_ID}"
      TELEGRAM_APP_API_HASH: "${TELEGRAM_APP_API_HASH}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

    volumes:
      - ./data/channels_db:/app/data/channels_db
      - ./sessions:/app/sessions

    command: ["python", "-m", "src.sync_worker.run_sync"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - weaviate
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      JOURNEY_AGENT_DB_PATH: /app/data/channels_db/users_channels.db
      CHANNEL_SYNC_INTERVAL_HOURS: "6"
      CHANNEL_MESSAGES_LIMIT: "10"
      WEAVIATE_URL: http://weaviate:8080
      JOURNEY_AGENT_SEED_TEST_CHANNELS: "true"
      TELEGRAM_APP_API_ID: "${TELEGRAM_APP_API_ID}"
      TELEGRAM_APP_API_HASH: "${TELEGRAM_APP_API_HASH}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./data/channels_db:/app/data/channels_db
      - ./data/tg_sessions:/app/sessions

volumes:
  weaviate-data: