services:
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    restart: unless-stopped
    environment:
      OCCURRENCE_WEIGHT: "0.001"
      EXTENSIONS_STORAGE_MODE: weaviate
      ENABLE_COMPOUND_SPLITTING: "false"
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
    expose:
      - "9999"

  weaviate:
    image: semitechnologies/weaviate:1.27.0
    depends_on:
      - contextionary
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6060:6060"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CONTEXTIONARY_URL: contextionary:9999
      CLUSTER_HOSTNAME: node1
    volumes:
      - weaviate-data:/var/lib/weaviate

volumes:
  weaviate-data:

